/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OgRouteImport } from './routes/og'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ManifestDotjsonRouteImport } from './routes/manifest[.]json'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as HandleRouteImport } from './routes/$handle'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListsIndexRouteImport } from './routes/lists.index'
import { Route as InboxIndexRouteImport } from './routes/inbox.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as HandleIndexRouteImport } from './routes/$handle.index'
import { Route as ListsIdRouteImport } from './routes/lists.$id'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as InboxNewRouteImport } from './routes/inbox.new'
import { Route as InboxConversationIdRouteImport } from './routes/inbox.$conversationId'
import { Route as HashtagTagRouteImport } from './routes/hashtag.$tag'
import { Route as ChessIdRouteImport } from './routes/chess.$id'
import { Route as ArticlesNewRouteImport } from './routes/articles.new'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStatsRouteImport } from './routes/admin.stats'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as HandleFollowingRouteImport } from './routes/$handle.following'
import { Route as HandleFollowersRouteImport } from './routes/$handle.followers'
import { Route as OgUserHandleRouteImport } from './routes/og.user.$handle'
import { Route as OgPostIdRouteImport } from './routes/og.post.$id'
import { Route as ArticlesIdEditRouteImport } from './routes/articles.$id.edit'
import { Route as HandlePIdRouteImport } from './routes/$handle.p.$id'
import { Route as HandleASlugRouteImport } from './routes/$handle.a.$slug'
import { Route as OgArticleHandleSlugRouteImport } from './routes/og.article.$handle.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotjsonRoute = ManifestDotjsonRouteImport.update({
  id: '/manifest.json',
  path: '/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HandleRoute = HandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InboxRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const HandleIndexRoute = HandleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HandleRoute,
} as any)
const ListsIdRoute = ListsIdRouteImport.update({
  id: '/lists/$id',
  path: '/lists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxNewRoute = InboxNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InboxRoute,
} as any)
const InboxConversationIdRoute = InboxConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => InboxRoute,
} as any)
const HashtagTagRoute = HashtagTagRouteImport.update({
  id: '/hashtag/$tag',
  path: '/hashtag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const ChessIdRoute = ChessIdRouteImport.update({
  id: '/chess/$id',
  path: '/chess/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesNewRoute = ArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const HandleFollowingRoute = HandleFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => HandleRoute,
} as any)
const HandleFollowersRoute = HandleFollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => HandleRoute,
} as any)
const OgUserHandleRoute = OgUserHandleRouteImport.update({
  id: '/user/$handle',
  path: '/user/$handle',
  getParentRoute: () => OgRoute,
} as any)
const OgPostIdRoute = OgPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => OgRoute,
} as any)
const ArticlesIdEditRoute = ArticlesIdEditRouteImport.update({
  id: '/articles/$id/edit',
  path: '/articles/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const HandlePIdRoute = HandlePIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => HandleRoute,
} as any)
const HandleASlugRoute = HandleASlugRouteImport.update({
  id: '/a/$slug',
  path: '/a/$slug',
  getParentRoute: () => HandleRoute,
} as any)
const OgArticleHandleSlugRoute = OgArticleHandleSlugRouteImport.update({
  id: '/article/$handle/$slug',
  path: '/article/$handle/$slug',
  getParentRoute: () => OgRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/bookmarks': typeof BookmarksRoute
  '/drafts': typeof DraftsRoute
  '/inbox': typeof InboxRouteWithChildren
  '/login': typeof LoginRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/notifications': typeof NotificationsRoute
  '/og': typeof OgRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$handle/followers': typeof HandleFollowersRoute
  '/$handle/following': typeof HandleFollowingRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/articles/new': typeof ArticlesNewRoute
  '/chess/$id': typeof ChessIdRoute
  '/hashtag/$tag': typeof HashtagTagRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/inbox/new': typeof InboxNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/lists/$id': typeof ListsIdRoute
  '/$handle/': typeof HandleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/$handle/a/$slug': typeof HandleASlugRoute
  '/$handle/p/$id': typeof HandlePIdRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
  '/og/post/$id': typeof OgPostIdRoute
  '/og/user/$handle': typeof OgUserHandleRoute
  '/og/article/$handle/$slug': typeof OgArticleHandleSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bookmarks': typeof BookmarksRoute
  '/drafts': typeof DraftsRoute
  '/login': typeof LoginRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/notifications': typeof NotificationsRoute
  '/og': typeof OgRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$handle/followers': typeof HandleFollowersRoute
  '/$handle/following': typeof HandleFollowingRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/articles/new': typeof ArticlesNewRoute
  '/chess/$id': typeof ChessIdRoute
  '/hashtag/$tag': typeof HashtagTagRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/inbox/new': typeof InboxNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/lists/$id': typeof ListsIdRoute
  '/$handle': typeof HandleIndexRoute
  '/admin': typeof AdminIndexRoute
  '/inbox': typeof InboxIndexRoute
  '/lists': typeof ListsIndexRoute
  '/$handle/a/$slug': typeof HandleASlugRoute
  '/$handle/p/$id': typeof HandlePIdRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
  '/og/post/$id': typeof OgPostIdRoute
  '/og/user/$handle': typeof OgUserHandleRoute
  '/og/article/$handle/$slug': typeof OgArticleHandleSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$handle': typeof HandleRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/bookmarks': typeof BookmarksRoute
  '/drafts': typeof DraftsRoute
  '/inbox': typeof InboxRouteWithChildren
  '/login': typeof LoginRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/notifications': typeof NotificationsRoute
  '/og': typeof OgRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$handle/followers': typeof HandleFollowersRoute
  '/$handle/following': typeof HandleFollowingRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/articles/new': typeof ArticlesNewRoute
  '/chess/$id': typeof ChessIdRoute
  '/hashtag/$tag': typeof HashtagTagRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/inbox/new': typeof InboxNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/lists/$id': typeof ListsIdRoute
  '/$handle/': typeof HandleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/$handle/a/$slug': typeof HandleASlugRoute
  '/$handle/p/$id': typeof HandlePIdRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
  '/og/post/$id': typeof OgPostIdRoute
  '/og/user/$handle': typeof OgUserHandleRoute
  '/og/article/$handle/$slug': typeof OgArticleHandleSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$handle'
    | '/admin'
    | '/analytics'
    | '/bookmarks'
    | '/drafts'
    | '/inbox'
    | '/login'
    | '/manifest.json'
    | '/notifications'
    | '/og'
    | '/search'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/$handle/followers'
    | '/$handle/following'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/stats'
    | '/admin/users'
    | '/articles/new'
    | '/chess/$id'
    | '/hashtag/$tag'
    | '/inbox/$conversationId'
    | '/inbox/new'
    | '/invite/$token'
    | '/lists/$id'
    | '/$handle/'
    | '/admin/'
    | '/inbox/'
    | '/lists/'
    | '/$handle/a/$slug'
    | '/$handle/p/$id'
    | '/articles/$id/edit'
    | '/og/post/$id'
    | '/og/user/$handle'
    | '/og/article/$handle/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/bookmarks'
    | '/drafts'
    | '/login'
    | '/manifest.json'
    | '/notifications'
    | '/og'
    | '/search'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/$handle/followers'
    | '/$handle/following'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/stats'
    | '/admin/users'
    | '/articles/new'
    | '/chess/$id'
    | '/hashtag/$tag'
    | '/inbox/$conversationId'
    | '/inbox/new'
    | '/invite/$token'
    | '/lists/$id'
    | '/$handle'
    | '/admin'
    | '/inbox'
    | '/lists'
    | '/$handle/a/$slug'
    | '/$handle/p/$id'
    | '/articles/$id/edit'
    | '/og/post/$id'
    | '/og/user/$handle'
    | '/og/article/$handle/$slug'
  id:
    | '__root__'
    | '/'
    | '/$handle'
    | '/admin'
    | '/analytics'
    | '/bookmarks'
    | '/drafts'
    | '/inbox'
    | '/login'
    | '/manifest.json'
    | '/notifications'
    | '/og'
    | '/search'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/$handle/followers'
    | '/$handle/following'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/stats'
    | '/admin/users'
    | '/articles/new'
    | '/chess/$id'
    | '/hashtag/$tag'
    | '/inbox/$conversationId'
    | '/inbox/new'
    | '/invite/$token'
    | '/lists/$id'
    | '/$handle/'
    | '/admin/'
    | '/inbox/'
    | '/lists/'
    | '/$handle/a/$slug'
    | '/$handle/p/$id'
    | '/articles/$id/edit'
    | '/og/post/$id'
    | '/og/user/$handle'
    | '/og/article/$handle/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HandleRoute: typeof HandleRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  BookmarksRoute: typeof BookmarksRoute
  DraftsRoute: typeof DraftsRoute
  InboxRoute: typeof InboxRouteWithChildren
  LoginRoute: typeof LoginRoute
  ManifestDotjsonRoute: typeof ManifestDotjsonRoute
  NotificationsRoute: typeof NotificationsRoute
  OgRoute: typeof OgRouteWithChildren
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArticlesNewRoute: typeof ArticlesNewRoute
  ChessIdRoute: typeof ChessIdRoute
  HashtagTagRoute: typeof HashtagTagRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ListsIdRoute: typeof ListsIdRoute
  ListsIndexRoute: typeof ListsIndexRoute
  ArticlesIdEditRoute: typeof ArticlesIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.json': {
      id: '/manifest.json'
      path: '/manifest.json'
      fullPath: '/manifest.json'
      preLoaderRoute: typeof ManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$handle': {
      id: '/$handle'
      path: '/$handle'
      fullPath: '/$handle'
      preLoaderRoute: typeof HandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/': {
      id: '/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof InboxRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$handle/': {
      id: '/$handle/'
      path: '/'
      fullPath: '/$handle/'
      preLoaderRoute: typeof HandleIndexRouteImport
      parentRoute: typeof HandleRoute
    }
    '/lists/$id': {
      id: '/lists/$id'
      path: '/lists/$id'
      fullPath: '/lists/$id'
      preLoaderRoute: typeof ListsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/new': {
      id: '/inbox/new'
      path: '/new'
      fullPath: '/inbox/new'
      preLoaderRoute: typeof InboxNewRouteImport
      parentRoute: typeof InboxRoute
    }
    '/inbox/$conversationId': {
      id: '/inbox/$conversationId'
      path: '/$conversationId'
      fullPath: '/inbox/$conversationId'
      preLoaderRoute: typeof InboxConversationIdRouteImport
      parentRoute: typeof InboxRoute
    }
    '/hashtag/$tag': {
      id: '/hashtag/$tag'
      path: '/hashtag/$tag'
      fullPath: '/hashtag/$tag'
      preLoaderRoute: typeof HashtagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chess/$id': {
      id: '/chess/$id'
      path: '/chess/$id'
      fullPath: '/chess/$id'
      preLoaderRoute: typeof ChessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/new': {
      id: '/articles/new'
      path: '/articles/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof ArticlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$handle/following': {
      id: '/$handle/following'
      path: '/following'
      fullPath: '/$handle/following'
      preLoaderRoute: typeof HandleFollowingRouteImport
      parentRoute: typeof HandleRoute
    }
    '/$handle/followers': {
      id: '/$handle/followers'
      path: '/followers'
      fullPath: '/$handle/followers'
      preLoaderRoute: typeof HandleFollowersRouteImport
      parentRoute: typeof HandleRoute
    }
    '/og/user/$handle': {
      id: '/og/user/$handle'
      path: '/user/$handle'
      fullPath: '/og/user/$handle'
      preLoaderRoute: typeof OgUserHandleRouteImport
      parentRoute: typeof OgRoute
    }
    '/og/post/$id': {
      id: '/og/post/$id'
      path: '/post/$id'
      fullPath: '/og/post/$id'
      preLoaderRoute: typeof OgPostIdRouteImport
      parentRoute: typeof OgRoute
    }
    '/articles/$id/edit': {
      id: '/articles/$id/edit'
      path: '/articles/$id/edit'
      fullPath: '/articles/$id/edit'
      preLoaderRoute: typeof ArticlesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$handle/p/$id': {
      id: '/$handle/p/$id'
      path: '/p/$id'
      fullPath: '/$handle/p/$id'
      preLoaderRoute: typeof HandlePIdRouteImport
      parentRoute: typeof HandleRoute
    }
    '/$handle/a/$slug': {
      id: '/$handle/a/$slug'
      path: '/a/$slug'
      fullPath: '/$handle/a/$slug'
      preLoaderRoute: typeof HandleASlugRouteImport
      parentRoute: typeof HandleRoute
    }
    '/og/article/$handle/$slug': {
      id: '/og/article/$handle/$slug'
      path: '/article/$handle/$slug'
      fullPath: '/og/article/$handle/$slug'
      preLoaderRoute: typeof OgArticleHandleSlugRouteImport
      parentRoute: typeof OgRoute
    }
  }
}

interface HandleRouteChildren {
  HandleFollowersRoute: typeof HandleFollowersRoute
  HandleFollowingRoute: typeof HandleFollowingRoute
  HandleIndexRoute: typeof HandleIndexRoute
  HandleASlugRoute: typeof HandleASlugRoute
  HandlePIdRoute: typeof HandlePIdRoute
}

const HandleRouteChildren: HandleRouteChildren = {
  HandleFollowersRoute: HandleFollowersRoute,
  HandleFollowingRoute: HandleFollowingRoute,
  HandleIndexRoute: HandleIndexRoute,
  HandleASlugRoute: HandleASlugRoute,
  HandlePIdRoute: HandlePIdRoute,
}

const HandleRouteWithChildren =
  HandleRoute._addFileChildren(HandleRouteChildren)

interface AdminRouteChildren {
  AdminPostsRoute: typeof AdminPostsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminStatsRoute: typeof AdminStatsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPostsRoute: AdminPostsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminStatsRoute: AdminStatsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface InboxRouteChildren {
  InboxConversationIdRoute: typeof InboxConversationIdRoute
  InboxNewRoute: typeof InboxNewRoute
  InboxIndexRoute: typeof InboxIndexRoute
}

const InboxRouteChildren: InboxRouteChildren = {
  InboxConversationIdRoute: InboxConversationIdRoute,
  InboxNewRoute: InboxNewRoute,
  InboxIndexRoute: InboxIndexRoute,
}

const InboxRouteWithChildren = InboxRoute._addFileChildren(InboxRouteChildren)

interface OgRouteChildren {
  OgPostIdRoute: typeof OgPostIdRoute
  OgUserHandleRoute: typeof OgUserHandleRoute
  OgArticleHandleSlugRoute: typeof OgArticleHandleSlugRoute
}

const OgRouteChildren: OgRouteChildren = {
  OgPostIdRoute: OgPostIdRoute,
  OgUserHandleRoute: OgUserHandleRoute,
  OgArticleHandleSlugRoute: OgArticleHandleSlugRoute,
}

const OgRouteWithChildren = OgRoute._addFileChildren(OgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HandleRoute: HandleRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  BookmarksRoute: BookmarksRoute,
  DraftsRoute: DraftsRoute,
  InboxRoute: InboxRouteWithChildren,
  LoginRoute: LoginRoute,
  ManifestDotjsonRoute: ManifestDotjsonRoute,
  NotificationsRoute: NotificationsRoute,
  OgRoute: OgRouteWithChildren,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArticlesNewRoute: ArticlesNewRoute,
  ChessIdRoute: ChessIdRoute,
  HashtagTagRoute: HashtagTagRoute,
  InviteTokenRoute: InviteTokenRoute,
  ListsIdRoute: ListsIdRoute,
  ListsIndexRoute: ListsIndexRoute,
  ArticlesIdEditRoute: ArticlesIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
